/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p88-g94cb0c5e
 *
 * Project: 'cmsis-litert.Debug+SSE-320-U85' 
 * Target:  'Debug+SSE-320-U85' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE320.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::Device:Native Driver:SysCounter@1.0.1 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.1 */
#define RTE_TIMEOUT      1
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.26.2 */
#define RTE_ETHOS_U_CORE_DRIVER
/* tensorflow::Data Exchange:Serialization:flatbuffers&tensorflow@1.26.2 */
#define RTE_DataExchange_Serialization_flatbuffers     /* flatbuffers */
/* tensorflow::Data Processing:Math:gemmlowp fixed-point&tensorflow@1.26.2 */
#define RTE_DataExchange_Math_gemmlowp     /* gemmlowp */
/* tensorflow::Data Processing:Math:kissfft&tensorflow@1.26.2 */
#define RTE_DataExchange_Math_kissfft     /* kissfft */
/* tensorflow::Data Processing:Math:ruy&tensorflow@1.26.2 */
#define RTE_DataProcessing_Math_ruy     /* ruy */
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.26.2 */
#define RTE_ML_TF_LITE     /* TF */


#endif /* RTE_COMPONENTS_H */
